package com.decadev.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Builder;
import lombok.Data;
import lombok.NonNull;

import javax.validation.constraints.NotNull;

@Data
@Builder
@DynamoDBTable(tableName = "MyFitPalUsers")

public class User {
    @DynamoDBHashKey(attributeName = "userId")
    @DynamoDBAutoGeneratedKey
    private String userId;

    @DynamoDBIndexHashKey(attributeName = "username", globalSecondaryIndexName = "usernameIndex")
    private String username;

    private String password;

    @DynamoDBAttribute(attributeName = "email")
    private String email;

    @DynamoDBAttribute(attributeName = "gymAccess")
    private GymAccess gymAccess;

    // Fitness assessment attributes
    @DynamoDBAttribute(attributeName = "fitnessGoal")
    private FitnessGoal fitnessGoal;

    @DynamoDBAttribute(attributeName = "fitnessLevel")
    private FitnessLevel fitnessLevel;

    @DynamoDBAttribute(attributeName = "availability")
    private String availability;

    public User (@NonNull String userId, @NonNull String username, @NonNull String password,@NonNull String email) {
        this.userId=userId;
        this.username= username;
        this.password=password;
        this.email=email;
    }

    public User(){}
}
