package com.decadev.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.decadev.converters.ExerciseListConverter;
import lombok.Data;

import java.util.List;

@Data
@DynamoDBTable(tableName = "WorkoutPlans")
public class WorkoutPlan {
    @DynamoDBHashKey(attributeName = "planId")
    @DynamoDBAutoGeneratedKey
    private String planId;

    @DynamoDBAttribute(attributeName = "userId")
    private String userId;

    @DynamoDBAttribute(attributeName = "workoutSession")
    private List<WorkoutSession> workoutSessions;

    @DynamoDBTypeConverted(converter = ExerciseListConverter.class)
    @DynamoDBAttribute(attributeName = "exercises")
    private List<Exercise> exercises;

    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute(attributeName = "fitnessGoal")
    private FitnessGoal fitnessGoal;

    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute(attributeName = "fitnessLevel")
    private FitnessLevel fitnessLevel;

    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute(attributeName = "gymAccess")
    private GymAccess gymAccess;

    @DynamoDBAttribute(attributeName = "availability")
    private Integer availability;

    @DynamoDBAttribute(attributeName = "generalAdvice")
    private String generalAdvice;
}

