package com.decadev.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.decadev.converters.ExerciseListConverter;
import lombok.Data;

import java.util.List;

@Data
@DynamoDBTable(tableName = "WorkoutSessions")
public class WorkoutSession {
    @DynamoDBHashKey(attributeName = "planId")
    @DynamoDBAutoGeneratedKey
    private String planId;

    @DynamoDBAttribute(attributeName = "day")
    private String day;

    @DynamoDBTypeConverted(converter = ExerciseListConverter.class)
    @DynamoDBAttribute(attributeName = "exercises")
    private List<Exercise> exercises;
}
