package com.decadev.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.util.List;

@Data
@DynamoDBTable(tableName = "WorkoutPlans")
public class WorkoutPlan {
    @DynamoDBHashKey(attributeName = "planId")
    @DynamoDBAutoGeneratedKey
    private String planId;

    @DynamoDBIndexHashKey(attributeName = "userId", globalSecondaryIndexName = "userId-index")
    private String userId;

    @DynamoDBAttribute(attributeName = "workoutSessionIds")
    private List<String> workoutSessionIds;

    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute(attributeName = "fitnessGoal")
    private FitnessGoal fitnessGoal;

    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute(attributeName = "fitnessLevel")
    private FitnessLevel fitnessLevel;

    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute(attributeName = "gymAccess")
    private GymAccess gymAccess;

    @DynamoDBAttribute(attributeName = "availability")
    private Integer availability;

    @DynamoDBAttribute(attributeName = "generalAdvice")
    private String generalAdvice;
}
//TODO: Consider additional exceptions to create for WorkoutPlan endpoint
